const Channel = require('../models/channel');
const { successResponse, errorResponse } = require('../utils/apiResponse');
const { parsePaginationParams } = require('../utils/paginationHelper');

/**
 * Get all channels with pagination and filtering
 * @route GET /api/admin/channel/list
 * @access Admin
 */
const getAllChannels = async (req, res) => {
  try {
    const { page, limit, skip } = parsePaginationParams(req.query.page, req.query.limit);
    const { search, campusId, categoryId, isPlatformChannel, sortBy = 'createdAt', sortOrder = 'desc' } = req.query;

    // Build filter object
    const filter = {};
    if (search) {
      filter.$or = [
        { name: { $regex: search, $options: 'i' } },
        { slug: { $regex: search, $options: 'i' } }
      ];
    }
    
    // Admin can filter by any campusId (validation happens at query level)
    if (campusId) {
      const mongoose = require('mongoose');
      if (mongoose.Types.ObjectId.isValid(campusId)) {
        filter.campusId = campusId;
      } else {
        // Skip invalid ObjectId silently for flexible admin filtering
        console.log(`⚠️ [Admin] Invalid campusId filter ignored: ${campusId}`);
      }
    }
    
    // Admin can filter by any categoryId (validation happens at query level)
    if (categoryId) {
      const mongoose = require('mongoose');
      if (mongoose.Types.ObjectId.isValid(categoryId)) {
        filter.category = categoryId;
      } else {
        // Skip invalid ObjectId silently for flexible admin filtering
        console.log(`⚠️ [Admin] Invalid categoryId filter ignored: ${categoryId}`);
      }
    }
    
    if (isPlatformChannel !== undefined) filter.isPlatformChannel = isPlatformChannel === 'true';

    // Build sort object
    const sort = {};
    sort[sortBy] = sortOrder === 'desc' ? -1 : 1;

    const channels = await Channel.find(filter)
      .populate('campusId', 'title slug')
      .populate('category', 'slug')
      .populate('createdBy', 'firstName lastName email')
      .sort(sort)
      .limit(limit)
      .skip(skip)
      .lean();

    const totalChannels = await Channel.countDocuments(filter);

    // Get message counts for each channel
    const Message = require('../models/chat-message');
    const channelIds = channels.map(channel => channel._id);
    const messageCounts = await Message.aggregate([
      { $match: { channelId: { $in: channelIds } } },
      { $group: { _id: '$channelId', messageCount: { $sum: 1 } } }
    ]);

    const messageCountMap = {};
    messageCounts.forEach(item => {
      messageCountMap[item._id.toString()] = item.messageCount;
    });

    const responseData = channels.map(channel => ({
      ...channel,
      messageCount: messageCountMap[channel._id.toString()] || 0
    }));

    return successResponse(res, 200, 'Channels retrieved successfully', {
      channels: responseData,
      pagination: {
        currentPage: page,
        totalPages: Math.ceil(totalChannels / limit),
        totalItems: totalChannels,
        itemsPerPage: limit,
        hasNextPage: (page * limit) < totalChannels,
        hasPrevPage: page > 1
      }
    }, 'channelsFetched');

  } catch (error) {
    console.error('Error fetching channels:', error);
    return errorResponse(res, 500, 'Failed to fetch channels', error.message);
  }
};

/**
 * Update channel by ID
 * @route PUT /api/admin/channel/update
 * @access Admin
 */
const updateChannelById = async (req, res) => {
  try {
    const { channelId } = req.query;
    const { name, campusId, category, isPlatformChannel } = req.body;

    if (!channelId) {
      return errorResponse(res, 400, 'Channel ID is required');
    }

    // Validate ObjectId format for channelId
    const mongoose = require('mongoose');
    if (!mongoose.Types.ObjectId.isValid(channelId)) {
      return errorResponse(res, 400, 'Invalid channelId format. Must be a valid 24-character ObjectId');
    }

    // Check if channel exists
    const existingChannel = await Channel.findById(channelId);
    if (!existingChannel) {
      return errorResponse(res, 404, 'Channel not found');
    }

    // Prepare update data (admin has full control)
    const updateData = {};
    if (name !== undefined) {
      updateData.name = name.trim();
      // The slug will be auto-generated by the pre-validate hook
    }
    if (campusId !== undefined) updateData.campusId = campusId || null; // Admin can set/unset campus
    if (category !== undefined) updateData.category = category || null;   // Admin can set/unset category
    if (isPlatformChannel !== undefined) updateData.isPlatformChannel = isPlatformChannel;

    // If name is being updated, check for duplicate slugs
    if (name && name.trim() !== existingChannel.name) {
      const slugify = require('slugify');
      const newSlug = slugify(name.trim(), { lower: true, strict: true });
      
      const duplicateChannel = await Channel.findOne({
        slug: newSlug,
        _id: { $ne: channelId }
      });
      
      if (duplicateChannel) {
        return errorResponse(res, 400, 'Channel with this name already exists');
      }
    }

    // Validate references if provided (admin can set/unset any references)
    if (campusId !== undefined) {
      if (campusId && !mongoose.Types.ObjectId.isValid(campusId)) {
        return errorResponse(res, 400, 'Invalid campusId format. Must be a valid 24-character ObjectId or null');
      }
      // Admin can assign/unassign campus freely - no existence check required
    }

    if (category !== undefined) {
      if (category && !mongoose.Types.ObjectId.isValid(category)) {
        return errorResponse(res, 400, 'Invalid category format. Must be a valid 24-character ObjectId or null');
      }
      // Admin can assign/unassign category freely - no existence check required
    }

    // Update channel
    const updatedChannel = await Channel.findByIdAndUpdate(
      channelId,
      updateData,
      { new: true, runValidators: true }
    )
    .populate('campusId', 'title slug')
    .populate('category', 'slug')
    .populate('createdBy', 'firstName lastName email');

    return successResponse(res, 200, 'Channel updated successfully', updatedChannel, 'channelUpdated');

  } catch (error) {
    console.error('Error updating channel:', error);
    return errorResponse(res, 500, 'Failed to update channel', error.message);
  }
};

/**
 * Delete channel by ID
 * @route DELETE /api/admin/channel/delete
 * @access Admin
 */
const deleteChannelById = async (req, res) => {
  try {
    const { channelId } = req.query;

    if (!channelId) {
      return errorResponse(res, 400, 'Channel ID is required');
    }

    // Validate ObjectId format
    const mongoose = require('mongoose');
    if (!mongoose.Types.ObjectId.isValid(channelId)) {
      return errorResponse(res, 400, 'Invalid channelId format. Must be a valid 24-character ObjectId');
    }

    // Check if channel exists
    const existingChannel = await Channel.findById(channelId);
    if (!existingChannel) {
      return errorResponse(res, 404, 'Channel not found');
    }

    // Get message count for info
    const Message = require('../models/chat-message');
    const messageCount = await Message.countDocuments({ channelId });

    // Admin deletion: Force delete all messages and channel (no campus restrictions)
    if (messageCount > 0) {
      await Message.deleteMany({ channelId });
      console.log(`🗑️ [Admin] Deleted ${messageCount} messages from channel ${existingChannel.name}`);
    }

    // Delete the channel regardless of campus or platform status
    await Channel.findByIdAndDelete(channelId);
    console.log(`🗑️ [Admin] Deleted channel: ${existingChannel.name} (${existingChannel.slug})`);

    return successResponse(res, 200, 'Channel and all associated messages deleted successfully', { 
      deletedChannelId: channelId,
      deletedChannelName: existingChannel.name,
      deletedChannelSlug: existingChannel.slug,
      deletedMessagesCount: messageCount,
      wasplatformChannel: existingChannel.isPlatformChannel,
      hadCampus: !!existingChannel.campusId
    }, 'channelDeleted');

  } catch (error) {
    console.error('Error deleting channel:', error);
    return errorResponse(res, 500, 'Failed to delete channel', error.message);
  }
};

/**
 * Create new channel
 * @route POST /api/admin/channel/create
 * @access Admin
 */
const createChannel = async (req, res) => {
  try {
    const { name, campusId, category, isPlatformChannel = false } = req.body;

    if (!name || !name.trim()) {
      return errorResponse(res, 400, 'Channel name is required');
    }

    // Validate ObjectId formats if provided
    const mongoose = require('mongoose');
    
    if (campusId && !mongoose.Types.ObjectId.isValid(campusId)) {
      return errorResponse(res, 400, 'Invalid campusId format. Must be a valid 24-character ObjectId');
    }
    
    if (category && !mongoose.Types.ObjectId.isValid(category)) {
      return errorResponse(res, 400, 'Invalid category format. Must be a valid 24-character ObjectId');
    }

    // Check if channel name already exists (slug collision)
    const slugify = require('slugify');
    const slug = slugify(name.trim(), { lower: true, strict: true });
    
    const existingChannel = await Channel.findOne({ slug });
    if (existingChannel) {
      return errorResponse(res, 400, 'Channel with this name already exists');
    }

    // Create channel data
    const channelData = {
      name: name.trim(),
      campusId: campusId || null,
      category: category || null,
      isPlatformChannel: isPlatformChannel,
      createdBy: null // Admin created, no specific user
    };

    // Create the channel
    const newChannel = await Channel.create(channelData);

    // Populate the response
    const populatedChannel = await Channel.findById(newChannel._id)
      .populate('campusId', 'title slug')
      .populate('category', 'slug')
      .lean();

    console.log(`✅ [Admin] Created new channel: ${newChannel.name} (${newChannel.slug})`);

    return successResponse(res, 201, 'Channel created successfully', populatedChannel, 'channelCreated');

  } catch (error) {
    console.error('Error creating channel:', error);
    return errorResponse(res, 500, 'Failed to create channel', error.message);
  }
};

module.exports = {
  getAllChannels,
  createChannel,
  updateChannelById,
  deleteChannelById
};
